LEARNING_RATE = 0.0001
IMAGE_SIZE = (224, 224)
TENSOR_SHAPE = (3,) + IMAGE_SIZE
BATCH_SIZE = 256
GPUS = 1
NUM_EPOCHS = 601

DATA_DIR = "./data"
TRAIN_DATA_DIR = f"{DATA_DIR}/train"
TEST_DATA_DIR = f"{DATA_DIR}/val"
